server:
  port: 8083

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://user-service:8080}
          predicates:
            - Path=/api/v1/users/**, /api/v1/cards/**
          filters:
            - name: JwtFilter

        - id: auth-service-protected
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/validate, /api/v1/auth/refresh
          filters:
            - name: JwtFilter

        - id: auth-service-public
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/login, /api/v1/auth/register

        - id: order-service-protected
          uri: ${ORDER_SERVICE_URI:http://order-service:8082}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtFilter

        - id: order-service-public
          uri: ${ORDER_SERVICE_URI:http://order-service:8082}
          predicates:
            - Path=/api/v1/items/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true

app:
  jwt:
    secret: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, gateway
      cors:
        allowed-origins: ${FRONTEND_CLIENT_URL:"http://localhost:3000"}
        allowed-methods: "GET, POST, OPTIONS"
        allowed-headers: "*"
        allow-credentials: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    gateway:
      enabled: true

otel:
  exporter:
    otlp:
      endpoint: ${TEMPO_SERVICE_URL:http://tempo:4317}
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none

