server:
  port: 8083

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtFilter

        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtFilter

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtFilter

        - id: user-service-swagger
          uri: http://user-service:8080
          predicates:
            - Path=/swagger/user/**
          filters:
            - RewritePath=/swagger/user/(?<segment>.*), /${segment}

        - id: auth-service-swagger
          uri: http://auth-service:8081
          predicates:
            - Path=/swagger/auth/**
          filters:
            - RewritePath=/swagger/auth/(?<segment>.*), /${segment}

        - id: order-service-swagger
          uri: http://order-service:8082
          predicates:
            - Path=/swagger/order/**
          filters:
            - RewritePath=/swagger/order/(?<segment>.*), /${segment}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: User Service
        url: /swagger/user/v3/api-docs
      - name: Auth Service
        url: /swagger/auth/v3/api-docs
      - name: Order Service
        url: /swagger/order/v3/api-docs
    deepLinking: true
    displayRequestDuration: true

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
