server:
  port: 8083

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://user-service:8080}
          predicates:
            - Path=/api/v1/users/**, /api/v1/cards/**
          filters:
            - name: JwtFilter

        - id: auth-service-protected
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/validate, /api/v1/auth/refresh
          filters:
            - name: JwtFilter

        - id: auth-service-public
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/login, /api/v1/auth/register

        - id: order-service
          uri: ${ORDER_SERVICE_URI:http://order-service:8082}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtFilter

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
