global:
  scrape_interval: 10s

scrape_configs:
  - job_name: spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - auth-service:8081
          - user-service:8080
          - order-service:8082
          - payment-service:8084
